### ISSUE TITLE
Download OpenPTV for 64-bit LINUX CentOS 7

### ISSUE THREAD

**Issue by KouJu** [OpenPTV/docs#5]
Now, I try to download OpenPTV.

I use CentOS 7.  Dose OpenPTV work in  **64-bit LINUX CentOS 7** ?

I reference this page [https://github.com/OpenPTV/docs/blob/master/docs/source/installation_instructions_for_64-bit_ubuntu_12.04_lts.txt](url)
When I put the comand below,
`$conda install --file alex_list.txt`
I got the error below
`CondaFileIOError: 'alex_list.txt'. [Errno 2] No such file or directory: 'alex_list.txt'`

Is  the version of Miniconda necessary to be Miniconda-3.0.0-Linux-x86_64.sh?
Could I use Miniconda3-latest-Linux-x86_64.sh?

Thank you.

**Comment by alexlib** [comment]
Hey @KouJu 

let's move to the forum https://groups.google.com/forum/#!forum/openptv - more people will see your question

regarding the installation, I think it's best to follow just these: 

```
python -m pip install --upgrade pip
pip install numpy
pip install pyptv --index-url https://pypi.fury.io/pyptv --extra-index-url https://pypi.org/simple
```

**Comment by KouJu** [comment]
Okay, I understand. Thank you @alexlib !

**Comment by KouJu** [comment]
> Hey @KouJu
> 
> let's move to the forum https://groups.google.com/forum/#!forum/openptv - more people will see your question
> 
> regarding the installation, I think it's best to follow just these:
> 
> ```
> python -m pip install --upgrade pip
> pip install numpy
> pip install pyptv --index-url https://pypi.fury.io/pyptv --extra-index-url https://pypi.org/simple
> ```

Hello, @alexlib 
How can I comment in the Forum[https://groups.google.com/forum/#!forum/openptv] ?

**Comment by alexlib** [comment]
i guess you asked to join. i approved one pending member.

**Comment by KouJu** [comment]
Thank you Alex!!

2019年8月27日(火) 3:22 Alex Liberzon <notifications@github.com>:
